server {
    listen 80;
    server_name _;

    root /app; 
    index login/index.php;

    location / {
        try_files $uri $uri/ /login/index.php;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}